### ISSUE TITLE
not sure abt change

### ISSUE THREAD

**Issue by kamalsenet** [kamalsenet/rainbow-poem#5]
doing something differently 
d6949f68cf5d833835541fb4886230f800ea6c84

**Comment by dearestmasud** [comment]
ok fixes #5

**Comment by dearestmasud** [comment]
![star](https://user-images.githubusercontent.com/86687017/162605241-adf2fc6f-225c-42fa-8b62-fd46e3d4b09e.png)

**Comment by kamalsenet** [comment]
🦈
